name: Build and Push Docker Images Using Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker username from GitHub secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker token from GitHub secrets

    - name: Build and Push Docker Compose Services
      run: |
        cd docker-compose/default  # Navigate to the folder containing the docker-compose.yml
        docker-compose build
        docker-compose push

    - name: Clean up
      run: |
        cd docker-compose/default  # Navigate again to ensure proper context for cleanup
        docker-compose down
